#!/usr/bin/env bash
# Recipe metadata is consumed by lib/applications.sh after sourcing.
# shellcheck disable=SC2034

AERO7_APP_ID="aero-gwenview"
AERO7_APP_NAME="Aero Gwenview"
AERO7_APP_AUTHOR="Albert Tomanek"
AERO7_APP_SOURCE_URL="https://gitgud.io/atmk/gwenview-aero"
AERO7_APP_REF="AUR package tracks upstream git"
AERO7_APP_LICENSE="GPL-2.0-or-later"
AERO7_APP_DEPENDENCIES="gwenview-aero-git"
AERO7_APP_OPTIONAL_DEPENDENCIES=""
AERO7_APP_SUPPORTED_SESSION="wayland"
AERO7_APP_BUILD_SYSTEM="aur"
AERO7_APP_SOURCE_SUBDIR="."
AERO7_APP_INSTALL_KIND="aur"
AERO7_APP_AUR_PACKAGE="gwenview-aero-git"
AERO7_APP_VALIDATE_COMMAND="command -v gwenview >/dev/null 2>&1"
AERO7_APP_FATAL="no"
AERO7_APP_EXPERIMENTAL="yes"
AERO7_APP_AVAILABLE="no"
AERO7_APP_REASON="AUR package conflicts with stock gwenview; disabled until an explicit replacement flow is implemented."
AERO7_APP_BRANCH="AUR package follows upstream default branch"
AERO7_APP_BUILD_COMMAND="disabled: conflicts with stock gwenview"
AERO7_APP_INSTALL_COMMAND="disabled: conflicts with stock gwenview"
AERO7_APP_UNINSTALL_METADATA="pacman package gwenview-aero-git; conflicts with stock gwenview"
AERO7_APP_PLASMA6_COMPAT="yes"
AERO7_APP_WAYLAND_COMPAT="yes"
AERO7_APP_REPLACES_PACKAGES="gwenview"
