#!/usr/bin/env bash
# Recipe metadata is consumed by lib/applications.sh after sourcing.
# shellcheck disable=SC2034

AERO7_APP_ID="aero-kolourpaint"
AERO7_APP_NAME="Aero KolourPaint"
AERO7_APP_AUTHOR="Albert Tomanek"
AERO7_APP_SOURCE_URL="https://invent.kde.org/albert-tomanek/kolourpaint.git"
AERO7_APP_REF="0a0debee63d9902b1dd6dafdddad41f21549c5b7"
AERO7_APP_LICENSE="GPL-2.0-or-later"
AERO7_APP_DEPENDENCIES="aero7-qt aero7-kolourpaint"
AERO7_APP_OPTIONAL_DEPENDENCIES=""
AERO7_APP_SUPPORTED_SESSION="wayland"
AERO7_APP_BUILD_SYSTEM="cmake"
AERO7_APP_SOURCE_SUBDIR="."
AERO7_APP_INSTALL_KIND="binary"
AERO7_APP_AUR_PACKAGE=""
AERO7_APP_BINARY_PACKAGE="aero7-kolourpaint"
AERO7_APP_VALIDATE_COMMAND="command -v kolourpaint >/dev/null 2>&1"
AERO7_APP_FATAL="no"
AERO7_APP_EXPERIMENTAL="yes"
AERO7_APP_AVAILABLE="yes"
AERO7_APP_REASON="Pinned Aero7 package built and smoke-tested with MIT SARibbon and the clean-room MIT Aero7Qt layer."
AERO7_APP_BRANCH="saribbon-aero pinned at 0a0debee63d9902b1dd6dafdddad41f21549c5b7"
AERO7_APP_BUILD_COMMAND="built by the pinned aero7-repo/aero7-kolourpaint PKGBUILD"
AERO7_APP_INSTALL_COMMAND="pacman -S --needed aero7/aero7-kolourpaint"
AERO7_APP_UNINSTALL_METADATA="pacman package aero7-kolourpaint; provides and conflicts with stock kolourpaint"
AERO7_APP_PLASMA6_COMPAT="native-build-pass"
AERO7_APP_WAYLAND_COMPAT="offscreen-smoke-pass; real-wayland-vm-pending"
