#!/usr/bin/env bash
# Recipe metadata is consumed by lib/applications.sh after sourcing.
# shellcheck disable=SC2034

AERO7_APP_ID="aero-dolphin"
AERO7_APP_NAME="Aero Dolphin"
AERO7_APP_AUTHOR="Albert Tomanek"
AERO7_APP_SOURCE_URL="https://gitgud.io/atmk/dolphin-aero"
AERO7_APP_REF="f0500fae7c4aadf75df23300557c0288404c6575"
AERO7_APP_LICENSE="GPL-2.0-or-later"
AERO7_APP_DEPENDENCIES="aero7-qt aero7-dolphin"
AERO7_APP_OPTIONAL_DEPENDENCIES=""
AERO7_APP_SUPPORTED_SESSION="wayland"
AERO7_APP_BUILD_SYSTEM="cmake"
AERO7_APP_SOURCE_SUBDIR="."
AERO7_APP_INSTALL_KIND="binary"
AERO7_APP_AUR_PACKAGE=""
AERO7_APP_BINARY_PACKAGE="aero7-dolphin"
AERO7_APP_VALIDATE_COMMAND="command -v dolphin >/dev/null 2>&1"
AERO7_APP_FATAL="no"
AERO7_APP_EXPERIMENTAL="yes"
AERO7_APP_AVAILABLE="yes"
AERO7_APP_REASON="Pinned Aero7 package built and smoke-tested against the clean-room MIT Aero7Qt compatibility layer."
AERO7_APP_BRANCH="upstream default branch pinned at f0500fae7c4aadf75df23300557c0288404c6575"
AERO7_APP_BUILD_COMMAND="built by the pinned aero7-repo/aero7-dolphin PKGBUILD"
AERO7_APP_INSTALL_COMMAND="pacman -S --needed aero7/aero7-dolphin"
AERO7_APP_UNINSTALL_METADATA="pacman package aero7-dolphin; provides and conflicts with stock dolphin"
AERO7_APP_PLASMA6_COMPAT="native-build-pass"
AERO7_APP_WAYLAND_COMPAT="offscreen-smoke-pass; real-wayland-vm-pending"
AERO7_APP_REPLACES_PACKAGES="dolphin"
