#!/usr/bin/env bash
# Recipe metadata is consumed by lib/applications.sh after sourcing.
# shellcheck disable=SC2034

AERO7_APP_ID="aero-gwenview"
AERO7_APP_NAME="Aero Gwenview"
AERO7_APP_AUTHOR="Albert Tomanek"
AERO7_APP_SOURCE_URL="https://gitgud.io/atmk/gwenview-aero"
AERO7_APP_REF="33e15a58e3017ab9a4e01070cc1e3b0138b3892d"
AERO7_APP_LICENSE="GPL-2.0-or-later"
AERO7_APP_DEPENDENCIES="aero7-qt aero7-gwenview"
AERO7_APP_OPTIONAL_DEPENDENCIES=""
AERO7_APP_SUPPORTED_SESSION="wayland"
AERO7_APP_BUILD_SYSTEM="cmake"
AERO7_APP_SOURCE_SUBDIR="."
AERO7_APP_INSTALL_KIND="binary"
AERO7_APP_AUR_PACKAGE=""
AERO7_APP_BINARY_PACKAGE="aero7-gwenview"
AERO7_APP_VALIDATE_COMMAND="command -v gwenview >/dev/null 2>&1"
AERO7_APP_FATAL="no"
AERO7_APP_EXPERIMENTAL="yes"
AERO7_APP_AVAILABLE="yes"
AERO7_APP_REASON="Pinned Aero7 package built and smoke-tested with original code-drawn controls and the MIT Aero7Qt compatibility layer."
AERO7_APP_BRANCH="upstream default branch pinned at 33e15a58e3017ab9a4e01070cc1e3b0138b3892d"
AERO7_APP_BUILD_COMMAND="built by the pinned aero7-repo/aero7-gwenview PKGBUILD"
AERO7_APP_INSTALL_COMMAND="pacman -S --needed aero7/aero7-gwenview"
AERO7_APP_UNINSTALL_METADATA="pacman package aero7-gwenview; provides and conflicts with stock gwenview"
AERO7_APP_PLASMA6_COMPAT="native-build-pass"
AERO7_APP_WAYLAND_COMPAT="offscreen-smoke-pass; real-wayland-vm-pending"
AERO7_APP_REPLACES_PACKAGES="gwenview"
