#!/usr/bin/env bash
# Recipe metadata is consumed by lib/applications.sh after sourcing.
# shellcheck disable=SC2034

AERO7_APP_ID="control-panel"
AERO7_APP_NAME="Linux Control Panel"
AERO7_APP_AUTHOR="ActuallyAridan"
AERO7_APP_SOURCE_URL="https://github.com/actuallyaridan/linux-control.git"
AERO7_APP_REF="280a1bda565faf085df5a48dd9ee03a44d127977"
AERO7_APP_LICENSE="GPL-3.0"
AERO7_APP_DEPENDENCIES="aero7-qt linux-control-panel"
AERO7_APP_OPTIONAL_DEPENDENCIES=""
AERO7_APP_SUPPORTED_SESSION="wayland"
AERO7_APP_BUILD_SYSTEM="cmake"
AERO7_APP_SOURCE_SUBDIR="."
AERO7_APP_INSTALL_KIND="binary"
AERO7_APP_AUR_PACKAGE=""
AERO7_APP_BINARY_PACKAGE="linux-control-panel"
AERO7_APP_VALIDATE_COMMAND="test -f /usr/share/applications/linux-controlpanel.desktop || command -v control >/dev/null 2>&1"
AERO7_APP_FATAL="no"
AERO7_APP_EXPERIMENTAL="yes"
AERO7_APP_AVAILABLE="yes"
AERO7_APP_REASON="Pinned Aero7 package built and smoke-tested with the clean-room MIT Aero7Qt compatibility layer."
AERO7_APP_BRANCH="main pinned at 280a1bda565faf085df5a48dd9ee03a44d127977"
AERO7_APP_BUILD_COMMAND="built by the pinned aero7-repo/linux-control-panel PKGBUILD"
AERO7_APP_INSTALL_COMMAND="pacman -S --needed aero7/linux-control-panel"
AERO7_APP_UNINSTALL_METADATA="pacman package linux-control-panel; desktop entry linux-controlpanel.desktop"
AERO7_APP_PLASMA6_COMPAT="native-build-pass"
AERO7_APP_WAYLAND_COMPAT="Plasma 6 Wayland supported"
