#!/usr/bin/env bash
# Recipe metadata is consumed by lib/applications.sh after sourcing.
# shellcheck disable=SC2034

AERO7_APP_ID="execbin"
AERO7_APP_NAME="execbin run dialog"
AERO7_APP_AUTHOR="catpswin56"
AERO7_APP_SOURCE_URL="https://gitgud.io/catpswin56/execbin.git"
AERO7_APP_REF="6127849ad534b07d44b278b14f2246cf43ada3b9"
AERO7_APP_LICENSE="AGPL-3.0-only"
AERO7_APP_DEPENDENCIES="execbin"
AERO7_APP_OPTIONAL_DEPENDENCIES=""
AERO7_APP_SUPPORTED_SESSION="wayland"
AERO7_APP_BUILD_SYSTEM="cmake"
AERO7_APP_SOURCE_SUBDIR="."
AERO7_APP_INSTALL_KIND="binary"
AERO7_APP_AUR_PACKAGE=""
AERO7_APP_BINARY_PACKAGE="execbin"
AERO7_APP_VALIDATE_COMMAND="command -v execbin >/dev/null 2>&1"
AERO7_APP_FATAL="no"
AERO7_APP_EXPERIMENTAL="yes"
AERO7_APP_AVAILABLE="yes"
AERO7_APP_REASON="Pinned Aero7 package passes build and startup tests with documented original Aero7 branding."
AERO7_APP_BRANCH="master pinned at 6127849ad534b07d44b278b14f2246cf43ada3b9"
AERO7_APP_BUILD_COMMAND="built by the pinned aero7-repo/execbin PKGBUILD"
AERO7_APP_INSTALL_COMMAND="pacman -S --needed aero7/execbin"
AERO7_APP_UNINSTALL_METADATA="pacman package execbin"
AERO7_APP_PLASMA6_COMPAT="native-build-pass"
AERO7_APP_WAYLAND_COMPAT="Plasma 6 Wayland supported"
