#!/usr/bin/env bash
# Recipe metadata is consumed by lib/applications.sh after sourcing.
# shellcheck disable=SC2034

AERO7_APP_ID="gadgets"
AERO7_APP_NAME="Gadgets"
AERO7_APP_AUTHOR="Aero7 project"
AERO7_APP_SOURCE_URL="https://github.com/memegeko/aero7-repo/tree/main/companions/aero7-gadgets"
AERO7_APP_REF="Aero7 1.0.0"
AERO7_APP_LICENSE="MIT"
AERO7_APP_DEPENDENCIES="aero7-gadgets"
AERO7_APP_OPTIONAL_DEPENDENCIES=""
AERO7_APP_SUPPORTED_SESSION="wayland"
AERO7_APP_BUILD_SYSTEM="cmake"
AERO7_APP_SOURCE_SUBDIR="."
AERO7_APP_INSTALL_KIND="binary"
AERO7_APP_AUR_PACKAGE=""
AERO7_APP_BINARY_PACKAGE="aero7-gadgets"
AERO7_APP_VALIDATE_COMMAND="test -d /usr/share/plasma/plasmoids/org.aero7.gadgets.clock && test -d /usr/share/plasma/plasmoids/org.aero7.gadgets.cpu && test -d /usr/share/plasma/plasmoids/org.aero7.gadgets.notes"
AERO7_APP_FATAL="no"
AERO7_APP_EXPERIMENTAL="yes"
AERO7_APP_AVAILABLE="yes"
AERO7_APP_REASON="Original Aero7 Clock, CPU Meter, and Notes widgets pass qmllint and local package builds."
AERO7_APP_BRANCH="Aero7-owned source"
AERO7_APP_BUILD_COMMAND="built by the aero7-repo/aero7-gadgets PKGBUILD"
AERO7_APP_INSTALL_COMMAND="pacman -S --needed aero7/aero7-gadgets"
AERO7_APP_UNINSTALL_METADATA="pacman package aero7-gadgets; provides and conflicts with win-gadgets"
AERO7_APP_PLASMA6_COMPAT="native-build-and-stage-pass"
AERO7_APP_WAYLAND_COMPAT="Plasma 6 QML lint pass; real-wayland-vm-pending"
