#!/usr/bin/env bash
# Recipe metadata is consumed by lib/applications.sh after sourcing.
# shellcheck disable=SC2034

AERO7_APP_ID="linver"
AERO7_APP_NAME="LinVer"
AERO7_APP_AUTHOR="WackyIdeas"
AERO7_APP_SOURCE_URL="https://gitgud.io/wackyideas/linver.git"
AERO7_APP_REF="087f2746703d9c885de2e1a4f6360314283703f4"
AERO7_APP_LICENSE="AGPL-3.0-only"
AERO7_APP_DEPENDENCIES="linver"
AERO7_APP_OPTIONAL_DEPENDENCIES=""
AERO7_APP_SUPPORTED_SESSION="wayland"
AERO7_APP_BUILD_SYSTEM="qmake"
AERO7_APP_SOURCE_SUBDIR="."
AERO7_APP_INSTALL_KIND="binary"
AERO7_APP_AUR_PACKAGE=""
AERO7_APP_BINARY_PACKAGE="linver"
AERO7_APP_VALIDATE_COMMAND="command -v linver >/dev/null 2>&1"
AERO7_APP_FATAL="no"
AERO7_APP_EXPERIMENTAL="yes"
AERO7_APP_AVAILABLE="yes"
AERO7_APP_REASON="Pinned Aero7 package passes build and startup tests with all bundled version branding replaced by documented original artwork."
AERO7_APP_BRANCH="master pinned at 087f2746703d9c885de2e1a4f6360314283703f4"
AERO7_APP_BUILD_COMMAND="built by the pinned aero7-repo/linver PKGBUILD"
AERO7_APP_INSTALL_COMMAND="pacman -S --needed aero7/linver"
AERO7_APP_UNINSTALL_METADATA="pacman package linver"
AERO7_APP_PLASMA6_COMPAT="native-build-pass"
AERO7_APP_WAYLAND_COMPAT="Plasma 6 Wayland supported"
