#!/usr/bin/env bash
# Recipe metadata is consumed by lib/applications.sh after sourcing.
# shellcheck disable=SC2034

AERO7_APP_ID="winxplorer"
AERO7_APP_NAME="WinXplorer"
AERO7_APP_AUTHOR="catpswin56"
AERO7_APP_SOURCE_URL="https://gitgud.io/catpswin56/winxplorer.git"
AERO7_APP_REF="9d2fae647e1bd9fc7f1dd53f36f8d5e160f4fddc"
AERO7_APP_LICENSE="GPL-3.0-or-later"
AERO7_APP_DEPENDENCIES="winxplorer"
AERO7_APP_OPTIONAL_DEPENDENCIES=""
AERO7_APP_SUPPORTED_SESSION="wayland"
AERO7_APP_BUILD_SYSTEM="cmake"
AERO7_APP_SOURCE_SUBDIR="."
AERO7_APP_INSTALL_KIND="binary"
AERO7_APP_AUR_PACKAGE=""
AERO7_APP_BINARY_PACKAGE="winxplorer"
AERO7_APP_VALIDATE_COMMAND="command -v winxplorer >/dev/null 2>&1"
AERO7_APP_FATAL="no"
AERO7_APP_EXPERIMENTAL="yes"
AERO7_APP_AVAILABLE="yes"
AERO7_APP_REASON="Pinned Aero7 package passes build and startup tests after all bundled bitmap controls and navigation audio were replaced or removed."
AERO7_APP_BRANCH="master pinned at archived revision 9d2fae647e1bd9fc7f1dd53f36f8d5e160f4fddc"
AERO7_APP_BUILD_COMMAND="built by the pinned aero7-repo/winxplorer PKGBUILD"
AERO7_APP_INSTALL_COMMAND="pacman -S --needed aero7/winxplorer"
AERO7_APP_UNINSTALL_METADATA="pacman package winxplorer"
AERO7_APP_PLASMA6_COMPAT="native-build-pass"
AERO7_APP_WAYLAND_COMPAT="Plasma 6 Wayland supported"
