[Aero7]
Channel=stable
Session=wayland
ReplacePlasmaLayout=ask
InstallWinXplorer=ask
InstallSevulet=ask
InstallWine=true
InstallFastfetch=true
InstallPlymouth=true
InstallStartMenu=true
InstallTaskSwitcher=true
InstallTerminalCompat=true
ApplyWallpaper=true
ApplyAvatar=true
Reboot=ask
BrowserTheming=false

