00-preflight=3
10-backup=5
20-system-update=7
30-base-dependencies=10
40-plasma-wayland=10
50-yay=3
55-binary-repository=4
60-aeroshell=16
70-aero-applications=14
80-plasma-layout=5
90-sddm=5
100-plymouth=8
110-fastfetch=2
120-wine=2
130-terminal-compat=2
140-validation=4
